# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8888

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.29.231.76:5432/XXXX
        username: postgres
        password: XXXX
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/
    freemarker:
        suffix: .ftl
        templateEncoding: UTF-8
        templateLoaderPath: classpath:/templates/
        content-type: text/html

# Mybatis配置
mybatis:
    typeAliasesPackage: cn.biikee.db.entity
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

